server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://10.88.0.188:3306/mall?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: analysis
    password: cisdi

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  page-size-zero: true
  params: count=countSql

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

